### ISSUE TITLE
Error connecting Ehrbase to Keycloak

### ISSUE THREAD

**Issue by agustinpallares94** [ehrbase/ehrbase#1010]
I am trying to deploy ehrbase with auth 2.0.

I deploy everything with containers

```
ehrbase:
    image: ehrbase/ehrbase:next
    ports:
      - 8080:8080
    networks:
      - ehrbase-net
    env_file:
      - .env.ehrbase
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
      SECURITY_AUTHTYPE: OAUTH
      SECURITY_OAUTH2USERROLE: USER
      SECURITY_OAUTH2ADMINROLE: ADMIN
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: http://localhost:8081/auth/realms/ehrbase


  ehrdb:
    image: ehrbase/ehrbase-postgres:latest
    ports:
      - 5432:5432
    networks:
      - ehrbase-net
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase
```

I create the realm as it comes in the tutorial but I get the following error:
`Unable to resolve the Configuration with the provided Issuer of "http://localhost:8081/auth/realms/ehrbase"
`
But if I access to: http://localhost:8081/auth/realms/ehrbase I can see the token that generates the keycloak
