### ISSUE TITLE
Cannot host postgres ehrdb on other port then 5432 docker

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/ehrbase#1209]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

latest everything

### Steps to reproduce

run docker-compose with an postgres ehrdb on another port then 5432

### Expected behavior

compose working

### Actual result

connection refused on DB 

```
docker-ehrbase-1  | SQL State  : 08001
docker-ehrbase-1  | Error Code : 0
docker-ehrbase-1  | Message    : Connection to ehrdb:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
docker-ehrbase-1  | 
docker-ehrbase-1  | 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
docker-ehrbase-1  | 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
docker-ehrbase-1  | 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:147)
docker-ehrbase-1  | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
docker-ehrbase-1  | 	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
docker-ehrbase-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
docker-ehrbase-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
docker-ehrbase-1  | 	... 122 common frames omitted
docker-ehrbase-1  | Caused by: org.postgresql.util.PSQLException: Connection to ehrdb:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

```

### Further information

```
#docker-compose-ehrbase.yml
version: '3'

services:
  ehrbase:
    image: ehrbase/ehrbase:next
    ports:
      - 8080:8080
    networks:
      - ehrbase-net
    environment:
      DB_URL: jdbc:postgresql://ehrdb:5433/ehrbase
      DB_USER_ADMIN: ehrbase
      DB_PASS_ADMIN: ehrbase
      SECURITY_AUTHTYPE: BASIC
      SECURITY_AUTHUSER: myuser
      SECURITY_AUTHPASSWORD: myPassword432
      SECURITY_AUTHADMINUSER: myadmin
      SECURITY_AUTHADMINPASSWORD: mySuperAwesomePassword123
      DB_USER: ehrbase_restricted
      DB_PASS: ehrbase_restricted
    depends_on:
      - ehrdb
    restart: on-failure

  ehrdb:
    image: ehrbase/ehrbase-postgres:latest
    ports:
      - 5433:5432
    networks:
      - ehrbase-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER_ADMIN: ehrbase
      EHRBASE_PASSWORD_ADMIN: ehrbase
      EHRBASE_USER: ehrbase_restricted
      EHRBASE_PASSWORD: ehrbase_restricted

networks:
  ehrbase-net: {}

```
