### ISSUE TITLE
EHRbase K8s deployment and non-root user

### ISSUE THREAD

**Issue by subigre** [ehrbase/ehrbase#1335]
### Background

When Pod Security Admission is configured with a cluster-wide AdmissionConfiguration file which sets either to `baseline` or `restricted`, EHRbase deployement failed to start due to pod security contraints violations.

The use of the following securityContext does not help due to the root user:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
```

As workaround, the following label has to be used on EHRbase namespace:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ehrbase
  labels:
    pod-security.kubernetes.io/enforce: privileged
```

### Enhancement

Use a non-root user in the Docker container

### Further information

Tested with `ehrbase: latest`, K8s `1.28.10` (RKE2 and K3s) and CIS profiles
