### ISSUE TITLE
EHRbase K8s deployment and healthcheck

### ISSUE THREAD

**Issue by subigre** [ehrbase/ehrbase#1337]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Environment information

```xml
<status>
    <ehrbase_version>2.2.0</ehrbase_version>
    <openehr_sdk_version>2.11.0</openehr_sdk_version>
    <archie_version>3.3.0</archie_version>
    <jvm_version>Eclipse Adoptium 21.0.3+9-LTS</jvm_version>
    <os_version>Linux amd64 6.8.0-31-generic</os_version>
    <postgres_version>PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1
        20231014, 64-bit</postgres_version>
</status>
```

### Steps to reproduce

1. Create a K8s deployment to deploy EHRbase on Kubernetes
2. Setup a `livenessProbe` and `readinessProbe`
    ```yaml
    livenessProbe:
      httpGet:
        path: ???
        port: https
    readinessProbe:
      httpGet:
        path: ???
        port: https
   ```

There is actually no endpoint to monitor EHRbase instance status properly if you enable OAuth2 security.

### Expected behavior

I would suggest to unprotect the Spring Boot Actuator `health` endpoint only to have `/management/health/readiness` and `/management/health/readiness` accessible by default and to use the following without the need to authenticate.
 
```yaml

livenessProbe:
  httpGet:
    path: /management/health/liveness
    port: https
 initialDelaySeconds: 10
readinessProbe:
  httpGet:
    path: /management/health/readiness
    port: https
  initialDelaySeconds: 10
```

### Actual result

- / = `404 Not Found`
- /management/health = `404 Not Found`
- /management/health/liveness = `404 Not Found`
- /management/health/readiness= `404 Not Found`

Even though there is a mechanism to set HTTP headers like `Authorization`: 
```yaml
livenessProbe:
  httpGet:
    path: /management/health/readiness
    port: https
    httpHeaders:
      - name: Authorization
        value: Basic ZWhyYmFzZTplaHJiYXNl
```
I have two problems here:
- Using Basic Auth, the credentials cannot be stored as a `Secret` and must be provided in the `values.yaml` file in clear text or as base64
- Using OAuth2, same issue than Basic Auth + how to manage access token lifespan ?
