### ISSUE TITLE
Deploying EHRBase with Postgres Database without Extensions

### ISSUE THREAD

**Issue by sidharthramesh** [ehrbase/ehrbase#508]
## Configuration information

- EHRbase version: v0.16.5
- PostgreSQL version: 13.3
- Operating System version: Linux

## Steps to reproduce ## 

I'm trying to get EHRBase running with a Postgres container without any extensions. This is the most common scenario while deploying to the cloud with managed databases. I've tried to follow the guide by @chevalleyc [here](https://github.com/ehrbase/ehrbase/blob/262cfbb354d8adca75c5cd8ab7f9cb9fbf98adc7/base/db-setup/README.md).

This is the docker-compose.yaml:
```
version: "3"
services:
  ehrbase:
    image: ehrbase/ehrbase:next
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/ehrbase"
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SERVER_AQLCONFIG_USEJSQUERY: "false"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: ehrbase
volumes:
  db-data:
```
There was some discrepancy in the name of the variable to disable using the JsQuery extension. According to [the guide](https://github.com/ehrbase/ehrbase/blob/262cfbb354d8adca75c5cd8ab7f9cb9fbf98adc7/base/db-setup/README.md), it's `server.aql.use-jsquery`, but in the default [application.yaml](https://github.com/ehrbase/ehrbase/blob/develop/application/src/main/resources/application.yml) it's `server.aqlConfig.useJsQuery` which translates to the environment variable `SERVER_AQLCONFIG_USEJSQUERY` in the above docker-compose.yml

## Actual result ##

Running migrations on the postgres database fails because postgres does not understand what "ext" means:
```
ehrbase_1     | 2021-05-23 13:56:18.376  INFO 8 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "ehr": 1
ehrbase_1     | 2021-05-23 13:56:18.516  INFO 8 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "ehr" to version 2 - ehr
db_1          | 2021-05-23 13:56:18.535 UTC [32] ERROR:  schema "ext" does not exist at character 160
db_1          | 2021-05-23 13:56:18.535 UTC [32] STATEMENT:  -- storeComposition common_im entities
db_1          |         -- CREATE TABLE "system" ---------------------------------------
db_1          |         CREATE TABLE ehr.system (
db_1          |                 id UUid PRIMARY KEY DEFAULT ext.uuid_generate_v4(),
db_1          |                 description TEXT NOT NULL,
db_1          |                 settings TEXT NOT NULL
db_1          |          )
ehrbase_1     | 2021-05-23 13:56:18.586 ERROR 8 --- [           main] o.f.core.internal.command.DbMigrate      : Migration of schema "ehr" to version 2 - ehr failed! Changes successfully rolled back.
ehrbase_1     | 2021-05-23 13:56:18.602  WARN 8 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException:
ehrbase_1     | Migration V2__ehr.sql failed
ehrbase_1     | ----------------------------
ehrbase_1     | SQL State  : 3F000
ehrbase_1     | Error Code : 0
ehrbase_1     | Message    : ERROR: schema "ext" does not exist
ehrbase_1     |   Position: 160
ehrbase_1     | Location   : db/migration/V2__ehr.sql (/file:/ehrbase.jar!/BOOT-INF/lib/base-0.16.5.jar!/db/migration/V2__ehr.sql)
ehrbase_1     | Line       : 44
ehrbase_1     | Statement  : -- storeComposition common_im entities
ehrbase_1     | -- CREATE TABLE "system" ---------------------------------------
ehrbase_1     | CREATE TABLE ehr.system (
ehrbase_1     |         id UUid PRIMARY KEY DEFAULT ext.uuid_generate_v4(),
ehrbase_1     |         description TEXT NOT NULL,
ehrbase_1     |         settings TEXT NOT NULL
ehrbase_1     |  )
```
All of the subsequent migrations also fail due to the same reason. I've only included these logs here for brevity. I've included the entire logs in [this pastebin](https://pastebin.com/xmshZC1G) if you're interested.

## Expected result (Acceptance Criteria) ##

The migrations must be successful on the base Postgres image without any extensions. All existing functionality of EHRBase should be present.

## Definition of Done ##

- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] No additional runtime warnings
