### ISSUE TITLE
Issues with ARM based Docker images

### ISSUE THREAD

**Issue by wlad** [ehrbase/ehrbase#604]
Multiarch Docker Image of EHRbase does not work properly on ARM machines (like Macbook M1 or AWS ARM instances) when the image was build on AMD64 based host.

for more background see https://github.com/ehrbase/ehrbase/issues/567

## Configuration information

- EHRbase version: 0.17.2

## Steps to reproduce ## 

- build EHRbase (multiarch or just for arm) on a AMD64 based machine
- run this image on a ARM based machine

## Actual result ##

EHRbase fails to start

## Expected result (Acceptance Criteria) ##

EHRbase starts and passes integration test properly

## Definition of Done ##

- [ ] multiarch build process is reproducable on all supported platforms
- [ ] multiarch images (ehrbase and db) execute without errors on all supported platforms (regardless which plaform the build host is based on)

- [ ] Merge Request approved
- [ ] integration tests passed
- [ ] Build without errors

**Comment by wlad** [comment]
FYI @sidharthramesh

**Comment by sidharthramesh** [comment]
Thank you @wlad. I'm also not sure why this issue happens. Seems like whenever the image is built on an Intel system, even using buildx, it doesn't really work on an ARM device. Seems like a docker/buildkit bug. Will try to investigate.

**Comment by sidharthramesh** [comment]
Hey @wlad, so creating the jar first using `mvn package` and then just copying it over to multi-arch image seems to work well. It's must faster to build too since the tests don't run on every architecture.

I've tested it on my M1 mac and it works fine. The image is on Dockerhub as `medblocks/ehrbase`. You can test it yourself.

This is the `Dockerfile`:
```Dockerfile
FROM openjdk:11.0.13-jre-slim-buster
COPY target/app.jar app.jar
RUN mkdir -p file_repo/knowledge/archetypes &&  mkdir -p file_repo/knowledge/operational_templates && mkdir -p file_repo/knowledge/templates
EXPOSE 8080
ENTRYPOINT ["java","-Dspring.profiles.active=docker" ,"-jar","/app.jar"]
```

and the Github Action used:

```yaml
name: Docker Image CI

on:
  push:
    tags:
      - "v*"

env:
  IMAGES: medblocks/ehrbase
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the tagged commit
      uses: actions/checkout@v2

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGES }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          /tmp/.buildx-cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn --batch-mode package

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        platforms: ${{ env.PLATFORMS }}
    
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    

```
