### ISSUE TITLE
New docker image does not recognise Admin variables

### ISSUE THREAD

**Issue by agustinpallares94** [ehrbase/ehrbase#934]
I am trying to deploy on a kubernetes erhbase:0.21.1 with the environment variables ADMINAPI_ACTIVE and ADMINAPI_ALLOWDELETEALL and it is not able to recognise them.

**Comment by stefanspiska** [comment]
@agustinpallares94 

this worked for me

```
      containers:
      - env:
        - name: ADMIN_API_ACTIVE
          value: "true"
        - name: ADMIN_API_ALLOW_DELETE_ALL
          value: "true"
```
